export const skills = [
  "React",
  "TypeScript",
  "HTML5",
  "JavaScript",
  "CSS3",
  "SASS",
  "Vue",
  "AWS",
  "Firebase",
  "Redux",
  "Vuetify",
  "Material UI",
  "REST API",
  "Tailwind CSS",
  "Bootstrap",
  "Node.js",
  "Docker",
  "Vite",
  "LocalStorage",
  "Axios",
  "Cookies",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "i18next",
  "SCRUM",
  "Slack",
  "Figma",
  "Windows",
  "macOS",
  "WebSockets",
  "Socket io",
  "Web Development",
  "User Experience (UX)",
  "Collaboration",
];

export const highlightedSkills = [
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "AWS",
  "SASS",
  "Firebase",
  "GitLab",
  "Git",
  "Collaboration",
  "REST API",
  "Jira",
  "i18next",
  "Figma",
  "Vite",
  "Axios",
  "WebSockets",
];

export const name: string = "Le Quoc Bao";
export const role: string = "Frontend Developer";
export const email: string = "baole07701@gmail.com";
export const linkIn: string =
  "https://www.linkedin.com/in/b%E1%BA%A3o-l%C3%AA-1131021a5/";
